# options

# window look and feel
set -wg automatic-rename on                            # 允许 tmux 根据窗格内运行的程序自动重命名窗口
set -g automatic-rename-format "Window"                # 当无法获取程序名时，默认窗口名为 Window
set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "     # 非活动窗口标签格式：显示索引，如果窗口名不是默认的 Window 则显示窗口名
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"             # 非活动窗口标签文字颜色为 rosewater
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_peach}"            # 上一个访问窗口标签文字为 peach 色
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"          # 窗口有活动时标签以红底白字高亮
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"         # 终端响铃时标签以粗体、红底白字高亮
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"    # 窗口标签之间的分隔符（-F 立即展开变量）
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "    # 当前活动窗口标签格式，同非活动标签格式
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"           # 当前活动窗口标签以 peach 背景、白字、粗体突出显示
