# plugins

# 2.插件配置
# ###############################################
set -g @plugin 'tmux-plugins/tpm'                      # 声明 tmux 插件管理器（TPM）自身
set -g @plugin 'tmux-plugins/tmux-battery'              # 声明电池插件，用于在状态栏显示电池电量和图标
set -g @plugin 'catppuccin/tmux'                        # 声明 Catppuccin 主题插件，提供配色和基本布局


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'                          # 启动 TPM，实际加载所有已安装的插件